#!/usr/bin/env bash
set -euo pipefail

# create-pr.sh
# Checks for uncommitted changes, creates a branch, commits, pushes,
# and opens a Pull Request via the GitHub CLI (gh).

# ── Parse arguments ────────────────────────────────────────────────────
BRANCH_PREFIX="kimchi-auto-fix-"
BASE_BRANCH=""
TITLE="[Kimchi Auto-Fix] Resolve failing CI pipeline"
COMMIT_MESSAGE="[Kimchi Auto-Fix] Resolve failing CI pipeline

This commit contains an automated fix generated by Kimchi Ferment.
The agent analyzed the test failure, identified the root cause,
and applied the minimal code change necessary to make the tests pass."
WORKING_DIRECTORY="$(pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch-prefix)
      BRANCH_PREFIX="$2"
      shift 2
      ;;
    --base-branch)
      BASE_BRANCH="$2"
      shift 2
      ;;
    --title)
      TITLE="$2"
      shift 2
      ;;
    --commit-message)
      COMMIT_MESSAGE="$2"
      shift 2
      ;;
    --working-directory)
      WORKING_DIRECTORY="$2"
      shift 2
      ;;
    *)
      echo "[create-pr] Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "[create-pr] Starting PR creation..."

# ── 1. Git sanity checks ─────────────────────────────────────────────

if ! command -v git &>/dev/null; then
  echo "[create-pr] ERROR: git is not installed."
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "[create-pr] ERROR: GitHub CLI (gh) is not installed."
  exit 1
fi

# ── 2. Capture base branch before any mutation ───────────────────────

if [[ -z "${BASE_BRANCH}" ]]; then
  BASE_BRANCH="$(git -C "${WORKING_DIRECTORY}" branch --show-current)"
fi

# ── 3. Check for changes ─────────────────────────────────────────────

if git -C "${WORKING_DIRECTORY}" diff --quiet && git -C "${WORKING_DIRECTORY}" diff --cached --quiet; then
  echo "[create-pr] No uncommitted changes found. Nothing to PR."
  exit 0
fi

# ── 4. Configure git identity if missing (required in CI) ────────────

GIT_AUTHOR_NAME="$(git -C "${WORKING_DIRECTORY}" config user.name 2>/dev/null || true)"
GIT_AUTHOR_EMAIL="$(git -C "${WORKING_DIRECTORY}" config user.email 2>/dev/null || true)"
if [[ -z "${GIT_AUTHOR_NAME}" ]]; then
  git -C "${WORKING_DIRECTORY}" config user.name "${GITHUB_ACTOR:-Kimchi Auto-Fix}"
fi
if [[ -z "${GIT_AUTHOR_EMAIL}" ]]; then
  git -C "${WORKING_DIRECTORY}" config user.email "${GITHUB_ACTOR:-kimchi}@users.noreply.github.com"
fi

# ── 5. Gather metadata ───────────────────────────────────────────────

BRANCH_NAME="${BRANCH_PREFIX}$(date +%s)"
CHANGED_FILES="$(git -C "${WORKING_DIRECTORY}" diff --name-only HEAD || true)"
if [[ -z "${CHANGED_FILES}" ]]; then
  CHANGED_FILES="$(git -C "${WORKING_DIRECTORY}" diff --name-only || true)"
fi

VALIDATION_INFO="Tests were re-run after the fix was applied."

# ── 6. Create branch and commit ──────────────────────────────────────

echo "[create-pr] Creating branch ${BRANCH_NAME}..."
git -C "${WORKING_DIRECTORY}" checkout -b "${BRANCH_NAME}"

echo "[create-pr] Staging changes..."
git -C "${WORKING_DIRECTORY}" add -A

echo "[create-pr] Committing changes..."
git -C "${WORKING_DIRECTORY}" commit -m "${COMMIT_MESSAGE}"

# ── 7. Push branch ───────────────────────────────────────────────────

echo "[create-pr] Pushing branch ${BRANCH_NAME}..."
git -C "${WORKING_DIRECTORY}" push origin "${BRANCH_NAME}"

# ── 8. Open Pull Request ─────────────────────────────────────────────

PR_BODY=$(cat <<EOF
## Summary
An automated fix was generated by Kimchi Ferment after analyzing the failing CI pipeline logs.

## Changes Made
\`\`\`
${CHANGED_FILES}
\`\`\`

## Validation
${VALIDATION_INFO}

## Notes
Generated automatically using Kimchi Ferment.
EOF
)

echo "[create-pr] Creating Pull Request..."
(
  cd "${WORKING_DIRECTORY}"
  gh pr create \
    --title "${TITLE}" \
    --body "${PR_BODY}" \
    --head "${BRANCH_NAME}" \
    --base "${BASE_BRANCH}"
)

echo "[create-pr] Pull Request created successfully."
exit 0
